### ISSUE TITLE
error launching dataset/ps_preprocess.py

### ISSUE THREAD

**Issue by crankyz** [media-sec-lab/BAM#1]
python dataset/ps_preprocess.py
Resamplping...: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "dataset/ps_preprocess.py", line 57, in <module>
    get_boundary_labels(partialspoof_path, data_type, data_cache_path, resolution=0.16)
  File "dataset/ps_preprocess.py", line 24, in get_boundary_labels
    labels = np.load(labels_path, allow_pickle=True).item()
  File "C:\Users\mje68pf\.conda\envs\bam\lib\site-packages\numpy\lib\npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Projects\\BAM\\wave\\segment_labels/train_seglab_0.16.npy'

**Comment by ZhongJiafeng-16** [comment]
sorry for late reply. The `train_seglab_0.16.npy` is segment-level label file in PartialSpoofV1.2. there are some suggesion for you.
- check that  your PartialSpoof(PS) dataset version is correct.
- check the variable `partialspoof_path` in `ps_preprocess.py` should be the path of PS dataset.
- In Windows systems, you should chang `/` to `\` in all path string.

Hope it helps. if there are any quesion, pelaese feel free to contact me.

**Comment by crankyz** [comment]
thanks for an answer, could you provide a link to this dataset.

**Comment by ZhongJiafeng-16** [comment]
@crankyz https://zenodo.org/records/5766198
